package com.goktech.olala.server.dao.sys;

import com.goktech.olala.server.pojo.sys.SysMenu;
import java.util.List;

public interface SysMenuDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    int deleteByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    int insert(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    SysMenu selectByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    List<SysMenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    int updateByPrimaryKey(SysMenu record);
}