package com.goktech.olala.server.dao.sys;

import com.goktech.olala.core.resp.RespUserVo;
import com.goktech.olala.server.pojo.sys.SysUser;

import java.util.Collection;
import java.util.List;

public interface SysUserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    SysUser selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    List<SysUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    int updateByPrimaryKey(SysUser record);


    SysUser selectByExample(SysUser record);

}